services:
  db:
    image: mariadb
    container_name: django-boilerplate--db
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: out=$$(mysqladmin ping -h 127.0.0.1 -P 3306 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: django-boilerplate--web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
volumes:
  db: